# tasks:
#   - name: aws-cli
#     env:
#       AWS_CLI_AUTO_PROMPT: on-partial
#     init: |
#       cd /workspace
#       curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#       unzip awscliv2.zip
#       sudo ./aws/install
#       cd $THEIA_WORKSPACE_ROOT
# vscode:
#   extensions:
#     - 42Crunch.vscode-openapi

# ports:
#   - name: frontend
#     port: 3000
#     onOpen: open-browser
#     visibility: public
#   - name: backend
#     port: 4567
#     visibility: public
#   - name: xray-daemon
#     port: 2000
#     visibility: public
tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      tasks:
  - name: react-js
    command: |
      cd frontend-react-js
      npm i
vscode:
  extensions:
    - 42Crunch.vscode-openapi

    - ms-azuretools.vscode-docker

    - esbenp.prettier-vscode

    - ms-python.python

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public